name: Check cmake version

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  check-cmake-version:
    strategy:
      matrix:
        os:
          - windows-2019
          - macos-13
          - macos-14
          - ubuntu-22.04

    runs-on: ${{ matrix.os }}

    steps:
      - name: <Setup> Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install gnu-sed coreutils

      - name: <Setup> Install ONNX Runtime dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y patchelf

      - name: Check cmake version
        run: cmake --version
